repos:
  - repo: local
    hooks:
      - id: update-treemap
        name: Actualizar estructura del proyecto
        entry: .venv/Scripts/python.exe treemap.py
        language: system
        pass_filenames: false
        always_run: true
      
      - id: update-dependencies
        name: Actualizar an√°lisis de dependencias
        entry: .venv/Scripts/python.exe analyze_dependencies.py
        language: system
        pass_filenames: false
        always_run: true